# Generated by Django 4.1.1 on 2022-11-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bares', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bares',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
