# Generated by Django 4.1.1 on 2022-11-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bares', '0002_alter_bares_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heladerias',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='restaurantes',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
